// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNbeNlSQb8NyHK-z-JlVQWicssGnzyJms',
    appId: '1:526848120057:android:eb5e568c30feed321ebe28',
    messagingSenderId: '526848120057',
    projectId: 'khidma-plus-52001',
    databaseURL: 'https://khidma-plus-52001-default-rtdb.firebaseio.com',
    storageBucket: 'khidma-plus-52001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5BfNUzCGqw8MqxMniI0-lM2TpbVteDJo',
    appId: '1:526848120057:ios:b3bb3d95bbe104641ebe28',
    messagingSenderId: '526848120057',
    projectId: 'khidma-plus-52001',
    databaseURL: 'https://khidma-plus-52001-default-rtdb.firebaseio.com',
    storageBucket: 'khidma-plus-52001.firebasestorage.app',
    androidClientId: '526848120057-l45ob8v3vmn5q90kfgpq3bptesa06lbl.apps.googleusercontent.com',
    iosClientId: '526848120057-6jvrqk0jrgl256mprugner9ffof6i3mf.apps.googleusercontent.com',
    iosBundleId: 'com.services.khadamat',
  );

}